on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' 

      - name: Install dependencies
        run: |
          pnpm install
          pipx install poetry --python $(which python)
          poetry install

      - name: Build
        run: |
          pnpm run ci
