on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-python@v6
        with:
          python-version: "3.11"
      - run: pnpm install && pip install -r requirements.txt && pip install -r requirements-dev.txt
      - run: pnpm run ci
