on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: |
          pnpm install
          pipx install poetry --python $(which python)
          poetry install
      - run: pnpm run ci
